language: node_js

node_js:
  - "8"

before_install:

install:

before_script:
  - npm install -g @angular/cli

script:
  - npm install

after_success:
  - ng build --prod

after_failure:


after_script:

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: travis-test

